site_name: Example course

theme:
  feature:
    tabs: true
  name: material

docs_dir: content
site_dir: docs

site_url: https://insper-education.github.io/active-handout-example-course/
repo_url: https://github.com/insper-education/active-handout-example-course
edit_uri: edit/main/content/
repo_name: active-handout-example-course

nav:
  - Home: index.md
  - Classes:
    - classes/01-ExampleClass/index.md
  - Laboratories:
    - labs/01-ExampleLab/index.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list

plugins: 
  - git-revision-date-localized
